[profile.dev]
codegen-backend = "cranelift"
package = { "*" = { codegen-backend = "llvm" } }

[target.'cfg(all(debug_assertions, target_os="linux"))']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Z", "share-generics=y", "-Z", "threads=8"]

[unstable]
codegen-backend = true

[build]
incremental = false # temporary workaround for https://github.com/rust-lang/rust/issues/139110
